### DISCUSSION TITLE
Devcontainer features don't work behind proxy if docker-compose.yml is used

### DISCUSSION THREAD

**Discussion by maederm** [devcontainers/community#128] [Q&A]
Hi

I have an issue using a devcontainers on Mac OS behind a tls-intercepting corporate proxy in vscode. Basically I can build the container using image and features. But when I use dockerComposeFile and features it gives me an error:

```log
ERROR: Feature "Poetry (via pipx)" (ghcr.io/devcontainers-contrib/features/poetry) failed to install
failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/poetry_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/poetry_0  && cd /tmp/dev-container-features/poetry_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/poetry_0" did not complete successfully: exit code: 7
```

I'm not really sure in which repo I should open the issue.

### Docker Compose that doesn't work
_devcontainer.json_
```json
{
	"name": "Python 3 docker-compose",
	"dockerComposeFile":[
		"docker-compose.yml"
	],
	"service": "devcontainer",
	"workspaceFolder": "/workspace",
	"features": {
		"ghcr.io/devcontainers-contrib/features/poetry:2": {}
	}
}
```
_docker-compose.yml_
```yml
version: '3.7'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
```

### Plain Image that works
_devcontainer.json_
```json
{
	"name": "Python 3 direct",
	"image": "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye",
	"features": {
		"ghcr.io/devcontainers-contrib/features/poetry:2": {}
	}
}
```

Do I miss something in the docker compose variant?

You can find the full logs and environment details here: https://github.com/maederm/devcontainer-proxy-issue
