### DISCUSSION TITLE
Dev Container and Pylance import error

### DISCUSSION THREAD

**Discussion by michaelxswe** [devcontainers/community#153] [General]
I have the following folder structure

```
C:.
│   docker-compose.yml
│   Dockerfile
│
├───.devcontainer
│       devcontainer.json
│
└───app
        __init__.py
        main.py
```

Dockerfile
```
FROM python:3.9 
```

docker-compose.yml
```
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/workspace
    command: sleep infinity
```

devcontainer.json
```
{
    "name": "app",
    "dockerComposeFile": "../docker-compose.yml",
    "service": "app",
    "workspaceFolder": "/workspace",
    "postCreateCommand": "",
    "customizations": {
        "vscode": {
            "extensions": [
                "ms-python.python",
                "charliermarsh.ruff"
            ],
            "settings": {
                "python.analysis.autoImportCompletions": true,
                "python.analysis.typeCheckingMode": "basic"
            }
        }
    }
}

```

Everytime I try to to create a new file such as creating sub.py under app/, and try to import it to main.py

main.py
```
from app.sub import abc
```

I will get this error message
```
Import "app.sub" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)
(module) app
```

This resolve by itself if I reload the window, or rebuild the container, or pip install new libraries.

Does anyone know how I can resolve this?
