### DISCUSSION TITLE
Define shorter image names in devcontainer.json

### DISCUSSION THREAD

**Discussion by kitingChris** [devcontainers/community#193] [Ideas]
I have the following devcontainer.json

```
{
	"name": "nextjs-testproject",
	"dockerComposeFile": ["../compose.devcontainer.yaml"],
	"service": "next-app-dev",
	"shutdownAction": "none",
	"remoteUser": "node",
	"workspaceFolder": "/app", 
	"postStartCommand": "cd next-app/ && yarn install"
  }
```

and compose.devcontainer.yaml
```
include:
  - compose.db.yaml

services:
  next-app-dev:
    image: vsc-nextjs-testproject/next-app-dev:latest
    build:
      context: ./next-app
      dockerfile: ../Dockerfile
      target: builder
    env_file:
      - ./.env
    volumes:
      - ./:/app:cached
    restart: always
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
        required: true
    command: sleep infinity
```

unfortunatelly the image name is still overriden by devcontainer cli with vsc-nextjs-testproject-ce7fac6b01aea927495ff344c431c1b01ab39d70290c5ad64ecdcca2a823dbcc-uid

My idea: add an "image" option for devcontainer.json to specify the image name.

```
{
	"name": "nextjs-testproject",
	"dockerComposeFile": ["../compose.devcontainer.yaml"],
	"service": "next-app-dev",
	"image": "vsc-nextjs-testproject/next-app-dev:latest",
	"shutdownAction": "none",
	"remoteUser": "node",
	"workspaceFolder": "/app", 
	"postStartCommand": "cd next-app/ && yarn install"
  }
```

Or at least make the image name shorter. Please!
