### DISCUSSION TITLE
comiting from devcontainer rewriting entire file and poluting git repository

### DISCUSSION THREAD

**Discussion by henriquesati** [devcontainers/community#202] [General]
commiting my files from vscode containers polluting my repo, even when I change a few lines, when I add the file to the working tree, it rewrites the entire file to commit. it is possible to do some config to map my workdir as a volume so I can commit from my desktop desktop? here is my current setup
docker-compose 
```
version: '3.9'

services:
  jenkins:
    build:  # Substitui o "image" padrão pelo seu Dockerfile
      context: .
      dockerfile: Jenkins.dockerfile
    container_name: jenkins
    ports:
      - "7070:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elixir_network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: "1"
    user: root

  elixir_app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      postis:
        condition: service_healthy
    container_name: elixir_app
    ports:
      - "4000:4000"
      - "8081:8080"
      - "443:443"
    networks:
      - elixir_network
    deploy:
      resources:
        limits:
          memory: 25GB
          cpus: "2"
    stdin_open: true
    tty: true

  postis:
    image: postgres
    container_name: postis
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: pedri
      POSTGRES_DB: teste10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elixir_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedri -d teste10"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  jenkins_home:

networks:
  elixir_network:
    driver: bridge
```
```
and my dockerfile at my root folder

FROM ubuntu:22.04

# Configurações de ambiente
ENV LANG=C.UTF-8
ENV HOME=/root

# Instala dependências básicas e configura o repositório Erlang/Elixir
RUN set -xe \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        wget \
        gnupg2 \
        build-essential \
        libncurses5-dev \
        libssl-dev \
        fop \
        xsltproc \
        ca-certificates \
        libssl-dev \
        pkg-config \
        git \
        unzip \
        make \
        bash \
        libreadline-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN set -xe \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && . "$HOME/.cargo/env" \
    && rustup install stable \
    && rustup default stable

# Instala Erlang via repositório oficial
RUN set -xe \
    && echo "deb http://binaries2.erlang-solutions.com/ubuntu/ jammy-esl-erlang-26 contrib" >> /etc/apt/sources.list \
    && wget -q https://binaries2.erlang-solutions.com/GPG-KEY-pmanager.asc -O - | apt-key add - \
    && apt-get update \
    && apt-get install -y --no-install-recommends esl-erlang \
    && rm -rf /var/lib/apt/lists/*

# Instalar asdf
RUN set -xe \
    && git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0 \
    && echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc \
    && echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc


RUN set -xe \
    && ~/.asdf/bin/asdf plugin add elixir \
    && ~/.asdf/bin/asdf install elixir 1.17.0\
    && ~/.asdf/bin/asdf global elixir 1.17.0\
    && ~/.asdf/bin/asdf reshim elixir

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
&& apt-get install -y nodejs \
&& npm install -g ts-node

#RUN chmod +x /app/ashandphoenix/assets/js/pix_parser.js

ENV PATH="/root/.asdf/installs/elixir/1.17.0/bin:$PATH"
RUN mix local.hex --force

WORKDIR /app
COPY . /app


# Define o comando padrão para o container
CMD ["/bin/bash"]

```
dev container file
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/docker-existing-docker-compose
{
	"name": "Existing Docker Compose (Extend)",

	// Update the 'dockerComposeFile' list if you have more compose files or use different names.
	// The .devcontainer/docker-compose.yml file contains any overrides you need/want to make.
	"dockerComposeFile": [
		"../jenkins/docker-compose.yml"
	],

	// The 'service' property is the name of the service for the container that VS Code should
	// use. Update this value and .devcontainer/docker-compose.yml to the real service name.
	"service": "elixir_app",


	"workspaceFolder": "/app"

}
```
it is possible to make a general configuration for this?
