### DISCUSSION TITLE
Cannot use the project's .env in my devcontainer docker-compose.yml?

### DISCUSSION THREAD

**Discussion by bgloss** [devcontainers/community#36] [Q&A]
I don't get the environment variables from my project's `.env` file into the `docker-compose.yml`setup with a pretty default project layout. 

My project layout is as follows:

```
.devcontainer/
     devcontainer.json
     docker-compose.yml
     Dockerfile
.env
```

I want to have in `docker-compose.yml` a section to create a Postgres container with setting up the environment one by one: `POSTGRES_USER`, `POSTGRES_PASSWORD`, and `POSTGRES_DB` and fill them with variables from the project's `.env` file. The relevant section in `docker-compose.yml` is: 
```
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
```

I do NOT want to have a copy of my `.env` file in the `.devcontainer/` folder, as it is the case in some of the DevContainer templates. This would work, as in this case `docker compose` loads it by default. I don't want this organization, as the `.env` file is also needed by the project's code and expected in the project root. 

I also don't want to expose the whole `.env`-file to my container, which I could do with the `env_file` option in the docker compose service description.

When building a container myself (just `docker`, no `docker compose`), I can add in `devcontainer.json` the option `runArgs` next to the option `build` giving the env-file information to docker: `--env-file ../.env` However, this is not possible when using a docker-compose setup in `vscode` and `DevContainers` with `"dockerComposeFile": "docker-compose.yml"`.

https://containers.dev/implementors/json_reference/

At the command line `docker compose --env-file ../.env up` does the trick.

So,  my questions:
- Am I missing something?
- Is this a missing feature in `devcontainer.json`?

**Comment by bamurtaugh** [comment]
Thanks for open this discussion. I've cross-posted this in our dev container community Slack channel to get some more perspectives. And if you'd like to join our community Slack, we'd love to have you join! https://github.com/orgs/devcontainers/discussions/3

**Comment by samruddhikhandale** [comment]
Hi 👋 

Can you add the following to your `docker-compose.yml` and see if it helps? Thanks! 

```
env_file:
      - ../.env
```

**Reply by samruddhikhandale** [reply]
If you are using the [postgres](https://github.com/devcontainers/templates/tree/main/src/postgres) Template, then you can add it on this line  [here](https://github.com/devcontainers/templates/blob/main/src/postgres/.devcontainer/docker-compose.yml#L17)

**Reply by bgloss** [reply]
This is not the solution. I explained in my post that it is not about providing the content of the .env-file into the postgres container, but to have the .env settings available in the docker-compose file. But ... thanks

**Comment by chrmarti** [comment]
There is a feature request for the Dev Containers extension to support `--env-file`: https://github.com/microsoft/vscode-remote-release/issues/4885. An implementation for this would also cover GitHub Codespaces.

**Comment by nelsonsilva94** [comment]
Is there a solution for this problem?

I am getting issues to use a .env file in devcontainer

**Reply by jusito** [reply]
A workaround which will helps in some cases:

_Layout from git root:_
.env
compose.yml
init/ (devcontainer folder)
init/compose.yml

`.devcontainer.json`:
```json
{
   "dockerComposeFile": [
        "compose.yml", // <- .env is used from this location
        "init/compose.yml"
    ]
   "service": "dev",
   ...
```

init/compose.yml just required to not include the other, not defining project name, and redefine volumes / networks as external:
E.g. `init/compose.yml`:
```yml
# This file is assumed to be consumed for devcontainer, not manually!
# npx @devcontainers/cli up --workspace-folder . (from git root)

networks:
  default:
    name: "fox_default"
    external: true

volumes:
  init-shared:
    name: "fox_init-shared"
    external: true

services:
  dev:
    ...
```
