### DISCUSSION TITLE
team development with remote devcontainers - disconnects whenever another developer builds image

### DISCUSSION THREAD

**Discussion by dss010101** [devcontainers/community#70] [General]
We have multiple developers working with the same code base in their remote devcontainer environment, but on the same dev server.  We are using vscode devcontainers.

I have the following docker compose which is designed to build/start user specific images and containers:
```
version: '3.8'
networks:
  app1_svc_net:
    driver: bridge

services:
  app1_svc:
    container_name: app1_svc_${USER_NAME} 
    image: "app1_svc_${USER_NAME}"  
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/${USER_NAME}/.ssh
    networks:
      - app1_svc_net
    command: bash -c "sleep infinity"
```

The env file looks like this:
```COMPOSE_PROJECT_NAME=app1_svc
ENV=local
USER_NAME=user1
USER_ID=1001
GROUP_ID=100
SVC_PORT=5010
PYTHONPATH=/workspaces/app1_svc/src
```

docker compose will pass some of the variables to the docker file as args. the dockerfile should create the user and start set the USER to the specific user
```
ARG ENV
ARG USER_NAME
ARG USER_ID
ARG GROUP_ID
...
RUN useradd -u $USER_ID -g $GROUP_ID $USER_NAME
USER $USER_NAME
```

Each developer has different settings for their .env file so that an image suffixed with their name is built as well as a container suffixed with their name is started.  I can see the different user specific images with different image ids, and i can also see the running dev containers with different user specific names.

The problem is though, is if im in my container, then another user builds their container, i get a disconnect, and when i reconnect, i am entering as that other user that just built/started their image and container.

Any ideas what may be going on here and how to solve
