### DISCUSSION TITLE
docker-compose samples network_mode

### DISCUSSION THREAD

**Discussion by sliekens** [devcontainers/community#79] [General]
Hi,

I've come across multiple Docker Compose samples where the main container uses `network_mode: service: db`. I think there are 2 reasons for this:

1. ~~to enable usage of "localhost" in connection strings, no matter where you run your code~~
2. to allow "portForwards" in devcontainer.json to function

https://containers.dev/guide/dockerfile#docker-compose-image

<details>

``` yml
version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
```

</details>

However I don't quite understand why the devcontainer uses the db's network adapter rather than the other way around.
It makes more sense to me to make this work the other way around by attaching the db to the devcontainer's network adapter.

``` diff
version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
-    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
+    network_mode: service:devcontainer
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
```

Does this work just as well, or is there a reason why you wouldn't do this?

**Comment by samruddhikhandale** [comment]
Hi 👋 

I have always added the `network_mode` property to the main container, it's interesting to see if the other way around works. 

However, according to my knowledge, the two code blocks would not produce the same behavior. In the first code block, the `db` service is using the network mode of another service called `devcontainer`. This means that the `db` service is connected to the `devcontainer` service's network. In the second code block, the `db` service is using the network mode of the `devcontainer` service. This means that the `db` service is connected to its own network, which is separate from the `devcontainer` service's network. 

The `devcontainer` service has access to the forwarded ports, which would no longer be the case if we use the second code block. Let me know if this doesn't make sense, or if you have any other questions. Thanks!

**Reply by sliekens** [reply]
Thanks for explaining. I'm still struggling to understand this. 😵‍💫

I tried it the other way and I can successfully connect from Azure Data Studio running on Windows to PostgreSQL running inside the container using port forwarding. For some reason I have to use the loopback address `127.0.0.1` instead of `localhost` but I think this is expected?

![image](https://github.com/devcontainers/community/assets/1583241/47fccdf1-d787-4e1c-ac3f-75de5609c1c9)


Config used:

- docker-compose.yml

``` yml
version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    network_mode: service:devcontainer
volumes:
  postgres-data:
```

- devcontainer.json

``` json
{
    "name": "PostgreSQL",
    "dockerComposeFile": "docker-compose.yml",
    "service": "devcontainer",
    "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
    "forwardPorts": [
        5432
    ]
}
```
